name: keyboard_visibility
description: Flutter plugin for discovering the state of the soft-keyboard visibility on Android and iOS.
version: 0.0.1
author: Onlly <412102100@qq.com>
homepage: https://github.com/mingyouzhu/flutter_keyboard_visibility

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.github.adee42.keyboardvisibility
    iosPrefix: FLT
    pluginClass: KeyboardVisibilityPlugin
